### ISSUE TITLE
scheduling abilities

### ISSUE THREAD

**Issue by LarsHolstHansen** [theSearchLife/smart-camera#1]
For the tests in the zoo it would be super benefical to have scheduling abilities in order to limit the system to only be active in certain periods in order to avoid recirding humans in the enclosure. I have Bern notified of the GDRP regulations which only allows to keep recordings with humans for 30 days. One option would obviously be to automatically delete such images but it may also be nice to avoid them altogether. 
The zoo have no monthly opening hours (with some exceptions). I will try to figure out how regular the human activity in the enclosures is (keepers cleaning).

**Comment by biolars** [comment]
Was this solved? Would be good with a pause every day 7-10.

**Comment by krasi-georgiev** [comment]
added
