### ISSUE TITLE
Fail-safe

### ISSUE THREAD

**Issue by LarsHolstHansen** [theSearchLife/smart-camera#2]
It would be beneficial to include some kind of fail-safe mechanism, to help ensure users do not get a false sense of security if some parts of the system is not working. This could be a malfunctioning camera or blocked view. One way to do this could be to trigger an alert if an expected target placed or naturally present in view is NOT detected. For the field deployment of the SBTS system, I plan to use such a method by placing traffic cones in camera view.

**Comment by krasi-georgiev** [comment]
added
